branches:
  only:
  - master
language: node_js
node_js:
- 9.10.0
before_install:
- sudo apt-get update
- sudo apt-get install -y python3 python3-pip
- pip3 install awscli --upgrade --user
install:
- npm install
script:
- npm run-script build
- npm run-script deploy
env:
  global:
  - secure: hYNF1OuTWN/SNUYkFrrEcBMt+7/r/T5CkrPBzDE1qLIsT8f/Rz8oCw28Z+K1hEneg6AEiUZHZIxv42YMjhBkgT9/beu3aShUscjA/lxLciH957zJMwpMD4X34fYCjD5i1WKzi31Fw4QWFo71Xgy4MCkcPjL7qRZ+TxdCHMatCxStfo8jnbeazVOPHGyVk1qhNC4/++J+zk1lA0j2UUHps/Aig+PItgb9NU7ncpSB+2ABfKjTO77xRwSAxVhFW/VCVPnymi9qknLdiBZEiretF3XSyPmmjswZ7QlF7Umj978mRMkbvPv6vg+K1p1rY5PiFlBorZd0VEpsn+kxxtOf0H5j+DZbpNQGj9GU714HnQ6kz00x1+DpOSvVIvMwLAKK4TpUzq+o8RsaPRQy2UW06TuvmRkkE73nqf0vcT17c5yESo4UumLnPmUrp6M+kvP10ZJFOcbJDKt2P9pJ0nyiptd5XuqCPqXgx+4MVwUIGFNljLPw07THkzUuiyF/UUopBQVmAvLGb85KJp+S83zybJdgqCV3P8ABa3rRMy9ok2hUVZfgCUk1YXOgUq5/rNMDo78GJraUhNAfakZBi2onsmVWZ+f0k5Puwv+uKUlfoxLAr9/5o0AjEx1tlblPaYfH2vNvJhWCVX3Rzf7Hpzb1HSJhtazHOR2R9Al45a1PXXc=
  - secure: dgg+ETVqQivrIgoVyBHtNK3DjGD8qdWoL//nzSpIKDBa+7KQddhJ2Xs/Ea968mQaiR+ClvETXfS0QodhxWMLxjGThBc5sRE3OJC5zROCBTKV27cl0CTAI4rPS9IZsqPgUD+GtL4bMFqgyLrJOGCD3/PZrVQJGsUCI1FVS0svaF9Yz0jMMz0pTAVso+Hdj640EFco6S3/JSZVdNMOq5as0WxLi4gvAaSnfY3D5zFXkyogQCSsUxaUBIGy2ltGp+wO++WZmawvFyafJfKDZZpNHZ5B7WzlVOVwDdeK3kdrGfj9UbAi3tWPYHJ8Ehyxf1YBCsMDgQgMluGP9QwatYbIQc+UnO/HfDhFODLGg7xpOvq1T0ofC07GS5M/zVMiULAMzW5IFZxI28NU9/pEBXExVl9EQDfY1DcOlrkEZX2xLbKepYksmGl+9sXSzeaaC9X+2jjkZdC61Ums4pddtJnHtOW3OMHfJeWWp6HPI4wMNWefTWvcB0ivWayA1V0lIuamA1QA///1AdKUZ5iKvhYhVGPy6huqY5ASlhnsxy0k3UETrZEAYMZNjTp/PbY4TL8wfnKFTV7OIDkaVZiKVCSTp3v/W1LAUBQyaxdPqM4UfNDzyYV7vAmqTGGu1+aDNW2D+H1n1wjeWDew2efjaTqq7rw0V4MZMKblwd8qD0qXCGY=
